# Generated by Django 2.2 on 2019-09-23 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeChatAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('create_time', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('openid', models.CharField(blank=True, max_length=32, verbose_name='微信账户 OpenID')),
                ('unionid', models.CharField(blank=True, max_length=32, verbose_name='微信账户 UnionID')),
                ('groupid', models.IntegerField(choices=[(0, '未知'), (1, '男'), (2, '女')], default=0, verbose_name='性别')),
                ('nickname', models.CharField(blank=True, default='', max_length=128, verbose_name='微信昵称')),
                ('city', models.CharField(blank=True, max_length=16, verbose_name='市')),
                ('province', models.CharField(blank=True, max_length=16, verbose_name='省')),
                ('subscribe_time', models.DateTimeField(verbose_name='订阅时间')),
                ('headimgurl', models.CharField(blank=True, max_length=25, verbose_name='头像 URL')),
                ('language', models.CharField(blank=True, max_length=16, verbose_name='语言')),
                ('remark', models.TextField(blank=True, verbose_name='备注')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='wechat', to=settings.AUTH_USER_MODEL, verbose_name='对方验证账号')),
            ],
            options={
                'verbose_name': '微信账户',
                'verbose_name_plural': '微信账户',
            },
        ),
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('role', models.CharField(blank=True, default='normal', max_length=16, verbose_name='用户角色')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='手机号')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱地址')),
                ('nickname', models.CharField(blank=True, default='', max_length=32, verbose_name='昵称')),
                ('sex', models.IntegerField(choices=[(0, '未知'), (1, '男'), (2, '女')], default=0, verbose_name='性别')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='头像')),
                ('avatar_url', models.CharField(blank=True, max_length=255, verbose_name='头像URL')),
                ('registration_source', models.IntegerField(default=0, verbose_name='注册来源')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='account', to=settings.AUTH_USER_MODEL, verbose_name='对应验证账号')),
            ],
            options={
                'verbose_name': '账户信息',
                'verbose_name_plural': '账户信息',
            },
        ),
    ]
