# Generated by Django 2.2 on 2020-02-16 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0002_auto_20200203_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songlist',
            name='user',
            field=models.CharField(max_length=50, verbose_name='点歌人'),
        ),
    ]
