# Generated by Django 2.2 on 2020-03-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('song', '0004_auto_20200216_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songlist',
            name='song',
            field=models.CharField(blank=True, max_length=50, verbose_name='歌名'),
        ),
    ]
