# Generated by Django 2.2 on 2020-01-29 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(blank=True, help_text='图片大小16:9', null=True, upload_to='banner', verbose_name='轮播图'),
        ),
    ]
